// import AnimeContext from '@/Helper/Context'
// import './globals.css'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body ><AnimeContext>{children}</AnimeContext></body>
//     </html>
//   )
// }

import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/Components/Header'
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ANIHUB4U',
  description: 'A anime reviewing platform',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#ffffff] dark:bg-[#242428] ${inter.className}`}>        
        <NextTopLoader color="#ffffff" />
        <Header />
        {children}
      </body>
    </html>
  )
}
